# Generated by Django 5.2.4 on 2025-08-31 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250823_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.municipality'),
        ),
    ]
