# Generated by Django 5.2.4 on 2025-08-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_department_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='municipality',
        ),
        migrations.AddField(
            model_name='department',
            name='municipalities',
            field=models.ManyToManyField(related_name='departments', to='base.municipality'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.municipality'),
            preserve_default=False,
        ),
    ]
